Repository Intro-to-SE-Spring-21/Group-9, pull requests merged in 2021-03, with the labels that each got.

#20 Class-Diagram-Final
  Class/Sequence Diagrams/Class Diagram.jpg
Labels: documentation

#21 Sequence-Diagrams-1-5
  Class/Sequence Diagrams/Create Account - Sequence Diagram.jpg
  Class/Sequence Diagrams/Follow - Sequence Diagram.jpg
  Class/Sequence Diagrams/Like - Sequence Diagram.jpg
  Class/Sequence Diagrams/Login - Sequence Diagram.jpg
  Class/Sequence Diagrams/Post - Sequence Diagram.jpg
Labels: documentation

#23 Comment - Sequence Diagram
  Class/Sequence Diagrams/Sequential Diagrams Template.jpg
Labels: documentation

#24 Comment - Sequence Diagram
  Class/Sequence Diagrams/Comment - Sequence Diagram.jpg
Labels: documentation

#25 Add Core Features and Edit Technologies
  README.md
Labels: documentation

#32 Core Feature 1 - Completed
  .htaccess
  .travis.yml
  README.md
  connect.php
  delete_account.php
  header.php
  home.php
  index.php
  login.php
  logout.php
  mysite/CSS/style.css
  mysite/HTML/index.html
  mysite/PHP/bootstrap.php
  mysite/PHP/connect.php
  mysite/PHP/footer.php
  mysite/PHP/header.php
  mysite/PHP/home.php
  mysite/PHP/index.php
  mysite/PHP/profile.php
  mysite/PHP/send_post.php
  mysite/SQL/users.sql
  phpunit.xml
  profile.php
  register.php
  search.php
  style.css
Labels: enhancement, priority - high, risk - high

#33 Core Feature 2 - Semi-Complete
  delete_account.php
  header.php
  home.php
  mysite/JS/main.js
  mysite/SQL/posts.sql
  posts.sql
  profile.php
  register.php
  style.css
  users.sql
Labels: enhancement
